
-- CLEAN SETUP: Purge recyclebin 
BEGIN
    EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
--------------------------------------------------------------


-- 1. PARENT TABLE: UTA_ENGAGE_USER

CREATE TABLE DASC5306_Fall25_S001_T2_UTA_Engage_User (
    netID               VARCHAR2(20)
        CONSTRAINT PK_USER PRIMARY KEY,
    username            VARCHAR2(50) NOT NULL,
    password            VARCHAR2(120) NOT NULL,
    enrolled_department VARCHAR2(90),
    street_address      VARCHAR2(100),
    apt                 VARCHAR2(20),
    county              VARCHAR2(50),
    zipcode             VARCHAR2(10),
    nationality         VARCHAR2(60),
    dob                 DATE,
    doe                 DATE,
    cumGPA              NUMBER(3,2)
);


-- 2. CHILD TABLES of UTA_ENGAGE_USER


-- 2.1 USER_EMAIL
CREATE TABLE DASC5306_Fall25_S001_T2_User_Email (
    netID  VARCHAR2(20) NOT NULL,
    email  VARCHAR2(120) NOT NULL,
    CONSTRAINT PK_USER_EMAIL PRIMARY KEY (netID, email),
    FOREIGN KEY (netID)
        REFERENCES DASC5306_Fall25_S001_T2_UTA_Engage_User(netID)
        ON DELETE CASCADE
);

-- 2.2 USER_PHONE
CREATE TABLE DASC5306_Fall25_S001_T2_User_Phone (
    netID        VARCHAR2(20) NOT NULL,
    phone_number VARCHAR2(10)
        CONSTRAINT CK_PHONE_10DIG CHECK (REGEXP_LIKE(phone_number, '^[0-9]{10}$')),
    CONSTRAINT PK_USER_PHONE PRIMARY KEY (netID, phone_number),
    FOREIGN KEY (netID)
        REFERENCES DASC5306_Fall25_S001_T2_UTA_Engage_User(netID)
        ON DELETE CASCADE
);


-- 3. ARTIST and PATRON (depend on USER)


CREATE TABLE DASC5306_Fall25_S001_T2_Artist (
    artistID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    netID               VARCHAR2(20) UNIQUE NOT NULL,
    number_of_followers NUMBER DEFAULT 0,
    subcount            NUMBER DEFAULT 0,
    FOREIGN KEY (netID)
        REFERENCES DASC5306_Fall25_S001_T2_UTA_Engage_User(netID)
        ON DELETE CASCADE
);

CREATE TABLE DASC5306_Fall25_S001_T2_Patron (
    patron_id VARCHAR2(20) PRIMARY KEY,
    netID     VARCHAR2(20) UNIQUE NOT NULL,
    FOREIGN KEY (netID)
        REFERENCES DASC5306_Fall25_S001_T2_UTA_Engage_User(netID)
        ON DELETE CASCADE
);


-- 4. PODCAST (depends on ARTIST)

CREATE TABLE DASC5306_Fall25_S001_T2_Podcast (
    podcastID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artistID          NUMBER NOT NULL,
    name              VARCHAR2(100) NOT NULL,
    creation_date     DATE DEFAULT SYSDATE,
    description       VARCHAR2(255),
    subscribers_count NUMBER DEFAULT 0,
    FOREIGN KEY (artistID)
        REFERENCES DASC5306_Fall25_S001_T2_Artist(artistID)
        ON DELETE CASCADE
);


-- 5. PODCAST_THEME (depends on PODCAST)

CREATE TABLE DASC5306_Fall25_S001_T2_Podcast_Theme (
    podcastID NUMBER NOT NULL,
    theme     VARCHAR2(50) NOT NULL
        CHECK (theme IN (
            'Educational','Travel','Interview','Storytelling',
            'Health and Fitness','News','Technology','Music',
            'Entertainment','Sports','Business','Art',
            'Cooking','Mindfulness','Comedy'
        )),
    CONSTRAINT PK_PODCAST_THEME PRIMARY KEY (podcastID, theme),
    FOREIGN KEY (podcastID)
        REFERENCES DASC5306_Fall25_S001_T2_Podcast(podcastID)
        ON DELETE CASCADE
);


-- 6. EPISODE (depends on PODCAST)

CREATE TABLE DASC5306_Fall25_S001_T2_Episode (
    episodeID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episodeNo       NUMBER NOT NULL,
    podcastID       NUMBER NOT NULL,
    title           VARCHAR2(150) NOT NULL,
    source_URL      VARCHAR2(255),
    format_FIELD    VARCHAR2(20)
        CHECK (format_FIELD IN ('Audio','Video')),
    upload_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration        NUMBER(5,2),
    views_count     NUMBER DEFAULT 0,
    likes_count     NUMBER DEFAULT 0,
    dislikes_count  NUMBER DEFAULT 0,
    FOREIGN KEY (podcastID)
        REFERENCES DASC5306_Fall25_S001_T2_Podcast(podcastID)
        ON DELETE CASCADE
);


-- 7. ADVERTISER (independent table)

CREATE TABLE DASC5306_Fall25_S001_T2_Advertiser (
    advertiserID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advertiser_name   VARCHAR2(100) NOT NULL,
    headquarters_city VARCHAR2(100),
    employees_count   NUMBER
);


-- 8. ADVERTISEMENT (depends on ADVERTISER and PODCAST)

CREATE TABLE DASC5306_Fall25_S001_T2_Advertisement (
    adID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advertiserID  NUMBER NOT NULL,
    podcastID     NUMBER NOT NULL,
    product_type  VARCHAR2(100),
    hyperlink     VARCHAR2(255),
    rate_per_view NUMBER(8,2),
    category      VARCHAR2(50),
    ad_duration   NUMBER(5,2),
    FOREIGN KEY (advertiserID)
        REFERENCES DASC5306_Fall25_S001_T2_Advertiser(advertiserID)
        ON DELETE CASCADE,
    FOREIGN KEY (podcastID)
        REFERENCES DASC5306_Fall25_S001_T2_Podcast(podcastID)
        ON DELETE CASCADE
);


-- 9. ASSOCIATED_WITH (depends on ADVERTISEMENT and EPISODE)

CREATE TABLE DASC5306_Fall25_S001_T2_Associated_with (
    adID          NUMBER NOT NULL,
    episodeID     NUMBER NOT NULL,
    timestamp_sec NUMBER(6,2),
    display_cost  NUMBER(8,2),
    CONSTRAINT PK_ASSOCIATED PRIMARY KEY (adID, episodeID, timestamp_sec, display_cost),
    FOREIGN KEY (adID)
        REFERENCES DASC5306_Fall25_S001_T2_Advertisement(adID)
        ON DELETE CASCADE,
    FOREIGN KEY (episodeID)
        REFERENCES DASC5306_Fall25_S001_T2_Episode(episodeID)
        ON DELETE CASCADE
);


-- 10. FOLLOW (depends on PATRON and ARTIST)

CREATE TABLE DASC5306_Fall25_S001_T2_Follow (
    patron_id   VARCHAR2(20) NOT NULL,
    artistID    NUMBER NOT NULL,
    status      VARCHAR2(10)
        CHECK (status IN ('Follow','Unfollow')),
    follow_date DATE DEFAULT SYSDATE,
    CONSTRAINT PK_FOLLOW PRIMARY KEY (patron_id, artistID),
    FOREIGN KEY (patron_id)
        REFERENCES DASC5306_Fall25_S001_T2_Patron(patron_id)
        ON DELETE CASCADE,
    FOREIGN KEY (artistID)
        REFERENCES DASC5306_Fall25_S001_T2_Artist(artistID)
        ON DELETE CASCADE
);


-- 11. SUBSCRIBE (depends on PATRON and PODCAST)

CREATE TABLE DASC5306_Fall25_S001_T2_Subscribe (
    patron_id      VARCHAR2(20) NOT NULL,
    podcastID      NUMBER NOT NULL,
    subscribe_date DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SUBSCRIBE PRIMARY KEY (patron_id, podcastID),
    FOREIGN KEY (patron_id)
        REFERENCES DASC5306_Fall25_S001_T2_Patron(patron_id)
        ON DELETE CASCADE,
    FOREIGN KEY (podcastID)
        REFERENCES DASC5306_Fall25_S001_T2_Podcast(podcastID)
        ON DELETE CASCADE
);


-- 12. LISTENING (depends on PATRON and EPISODE)

CREATE TABLE DASC5306_Fall25_S001_T2_Listening (
    patron_id       VARCHAR2(20) NOT NULL,
    episodeID       NUMBER NOT NULL,
    listen_date     DATE DEFAULT SYSDATE,
    location        VARCHAR2(100),
    listen_duration NUMBER(6,2),
    listen_count    NUMBER DEFAULT 1,
    CONSTRAINT PK_LISTENING PRIMARY KEY (patron_id, episodeID, listen_date),
    FOREIGN KEY (patron_id)
        REFERENCES DASC5306_Fall25_S001_T2_Patron(patron_id)
        ON DELETE CASCADE,
    FOREIGN KEY (episodeID)
        REFERENCES DASC5306_Fall25_S001_T2_Episode(episodeID)
        ON DELETE CASCADE
);


-- 13. CREATES (depends on ARTIST and PODCAST)

CREATE TABLE DASC5306_Fall25_S001_T2_Creates (
    artistID NUMBER NOT NULL,
    podcastID NUMBER NOT NULL,
    netID VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_CREATES PRIMARY KEY (artistID, podcastID),
    FOREIGN KEY (artistID)
        REFERENCES DASC5306_Fall25_S001_T2_Artist(artistID)
        ON DELETE CASCADE,
    FOREIGN KEY (podcastID)
        REFERENCES DASC5306_Fall25_S001_T2_Podcast(podcastID)
        ON DELETE CASCADE,
    FOREIGN KEY (netID)
        REFERENCES DASC5306_Fall25_S001_T2_Artist(netID)
        ON DELETE CASCADE
);

--------------------------------------------------------------
COMMIT;
