-- ===========================================================
-- DASC5306_Fall25_S001_T2 - COMPLETE CLEANUP SCRIPT
-- Purpose: Drop all triggers and tables in correct order
-- ===========================================================

--  Drop all triggers associated with this schema
BEGIN
    FOR rec IN (
        SELECT trigger_name 
        FROM user_triggers
        WHERE UPPER(trigger_name) LIKE 'DASC5306_FALL25_S001_T2%'
           OR UPPER(table_name) LIKE 'DASC5306_FALL25_S001_T2%'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TRIGGER ' || rec.trigger_name;
    END LOOP;
END;
/
PROMPT → All schema triggers removed.


--  Drop dependent tables first (child → parent)
-- Each DROP runs independently so script never halts mid-execution.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Associated_with CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Listening CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Subscribe CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Follow CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Podcast_Theme CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Episode CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Advertisement CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Creates CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_User_Email CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_User_Phone CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--Drop middle-level entities
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Podcast CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Artist CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Patron CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_Advertiser CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop the base user table last
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DASC5306_Fall25_S001_T2_UTA_Engage_User CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Optional workspace cleanup
BEGIN
    EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

COMMIT;

